### ISSUE TITLE
Current Render Engine structure makes 'w' (wait) command implementation impossible

### ISSUE THREAD

**Issue by sinabakh** [arendelle/sitron#1]
Current structure waits for Arendelle to build screen matrix, then renders it.

**Comment by sinabakh** [comment]
Since Rendering is based on the common way (clear/compute/draw) which is in infinite loop till the window is closed we can't change the logic in any of these two ways:
1. Breaking the loop will make the window freeze.
2. Changing the rendering algorithm is not acceptable because GPUs are optimized for this kind of calculations.

So it seems there is only one way to fix it, using multi-threaded algorithm. The rendering will take place in a different thread.

**Comment by sinabakh** [comment]
[Fixed.](https://github.com/arendelle/sitron/commit/52ee38bbb59122328b3ee9a3389859708d176083)
For now we use multi-threading.
I hope it don't make problems in other OSes (read Windows).

**Comment by pouyakary** [comment]
Cool! that's really cool! It happened with stuff like that in Swifty and Arendelle IDE iOS. It seems experiences happens over and over again :smile:
