### ISSUE TITLE
Compile and install

### ISSUE THREAD

**Issue by mohsend** [arendelle/sitron#10]
Looks like the compiling process can use some enhancements. Adding a `.\configure` script can go a long way. Even if I have no prior experience about these kinds of scripts, I might consider it a challenge for myself and have a go at it. 
First try of `make` form Beta 2 release (LMDE2 Linux x64):

```
 sitron-0.2.0-beta.2/ $ make
YACC Bison Building
bison -d -o ./Parser/parser.cpp ./Parser/parser.y
./Parser/parser.y:66.29-33: warning: symbol block is used, but is not defined as a token and has no rules [-Wother]
 %type <block> program stmts block func_decl
                             ^^^^^
./Parser/parser.y:66.35-43: warning: symbol func_decl is used, but is not defined as a token and has no rules [-Wother]
 %type <block> program stmts block func_decl
                                   ^^^^^^^^^
./Parser/parser.y:89.14-16: warning: type clash on default action: <expr> != <cmd> [-Wother]
 expr : mel | cmd | loop | condition | space_decl
              ^^^
./Parser/parser.y: warning: 2 nonterminals useless in grammar [-Wother]
./Parser/parser.y:66.29-33: warning: nonterminal useless in grammar: block [-Wother]
 %type <block> program stmts block func_decl
                             ^^^^^
./Parser/parser.y:66.35-43: warning: nonterminal useless in grammar: func_decl [-Wother]
 %type <block> program stmts block func_decl
                                   ^^^^^^^^^
./Parser/parser.y: warning: 9 shift/reduce conflicts [-Wconflicts-sr]
LEX Flex Building
flex -o ./Lexer/tokens.cpp ./Lexer/tokens.l
make: flex: Command not found
Makefile:20: recipe for target 'lexer' failed
make: *** [lexer] Error 127
```

And running `arendelle` binary form Beta 2 release:

```
 Downloads/ $ ./arendelle 
./arendelle: error while loading shared libraries: libsfml-graphics.so.2: cannot open shared object file: No such file or directory
```

I can also help by making `.deb` packages.

**Comment by pouyakary** [comment]
That would be cool. however Sitron may not ever be completed as we've started to move Arendelle to web, targeting a unified experience over all devices. For now @sinabakh  is developing an [Arendelle to JavaScript Compiler](https://github.com/sinabakh/arendelle-js-core) so that we can get native JS on web for exciting Arendelle. 

Thus I think all other engines: [JArendelle](https://github.com/arendelle/jarendelle), [Swifty](https://github.com/arendelle/swifty) and [Sitron](https://github.com/arendelle/sitron) will eventually be discontinued like the way  [Arcade](https://github.com/arendelle/arcade) did last year and may never run any version of Arendelle after `2XIV`

**Comment by mohsend** [comment]
Well I saw that the last commit was 11 days ago and assumed the project is active. But I can say I too think JS is the way to go. Maybe I can help maintaining `npm` packages there? I will have a look at the JS implantation repo and see how can I help.

**Comment by pouyakary** [comment]
Yeah JS is somehow the best solution for Arendelle as it's native and speedy, runs everywhere, is on the wab... there are several projects started in the past two weeks to move to web. The [compiler](https://github.com/sinabakh/arendelle-js-core) is the one you saw but more than that are are also the [auto-suggestion / refactoring server](https://github.com/arendelle/gerda] and the [IDE](https://github.com/arendelle/studio] that all together will be the new Arendelle experience.

**Comment by sinabakh** [comment]
First, thank you @mohsend for your interest in Sitron and helping to make it better.

Also, as Pouya mentioned, we are working on the web version. the JS core general structure is not in a good shape and needs an overhaul.

For now I am just trying to deliver a working core to the team.
